### ISSUE TITLE
FMD2 Update failing

### ISSUE THREAD

**Issue by Kpalaz** [Banh-Canh/docker-FMD2#11]
Container fails to update FMD2 form  Version: 2.0.31.0 to Version 2.0.32.0.

WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
Traceback (most recent call last):
  File "/usr/bin/websockify", line 11, in <module>
    load_entry_point('websockify==0.9.0', 'console_scripts', 'websockify')()
  File "/usr/lib/python3/dist-packages/websockify/websocketproxy.py", line 726, in websockify_init
    server.start_server()
  File "/usr/lib/python3/dist-packages/websockify/websockifyserver.py", line 737, in start_server
    lsock = self.socket(self.listen_host, self.listen_port, False,
  File "/usr/lib/python3/dist-packages/websockify/websockifyserver.py", line 488, in socket
    sock.bind(addrs[0][4])
OSError: [Errno 98] Address already in use

**Comment by Banh-Canh** [comment]
i'll update the image thanks for the report

**Comment by Banh-Canh** [comment]
Done, quick & dirty, i'll tag version accordingly one day, but it's all in the latest and unstable tags (need to repull the image).

**Comment by slhx99** [comment]
Hi,

I'm having the same issue too for the latest image:

BScreen::BScreen: an error occured while querying the X server.
	another window manager already running on display:1
Error: Couldn't find screens to manage.
Make sure you don't have another window manager running.
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
Traceback (most recent call last):
  File "/usr/bin/websockify", line 11, in <module>
    load_entry_point('websockify==0.9.0', 'console_scripts', 'websockify')()
  File "/usr/lib/python3/dist-packages/websockify/websocketproxy.py", line 726, in websockify_init
    server.start_server()
  File "/usr/lib/python3/dist-packages/websockify/websockifyserver.py", line 737, in start_server
    lsock = self.socket(self.listen_host, self.listen_port, False,
  File "/usr/lib/python3/dist-packages/websockify/websockifyserver.py", line 488, in socket
    sock.bind(addrs[0][4])
OSError: [Errno 98] Address already in use

**Comment by DieselTech** [comment]
@Banh-Canh This issue is still in the current docker image. I'm not able to roll back images because the old version has been deleted on dockerhub.

**Comment by DieselTech** [comment]
Update: I renamed my wine folder and let it create a new one from scratch and it at least is getting the container up and running now. It's just having a problem launching the fmd.exe file because of permission problems.

**Comment by abwezi** [comment]
@DieselTech Did you resolve this? I am trying other alternatives ATM because I am also affected by this problem, but I am not liking them as much. There seems to be nothing else to easily automate only downloading the newest chapters of a manga from instead of the entire thing.

**Comment by DieselTech** [comment]
> @DieselTech Did you resolve this? I am trying other alternatives ATM because I am also affected by this problem, but I am not liking them as much. There seems to be nothing else to easily automate only downloading the newest chapters of a manga from instead of the entire thing.

Yeah I was able to get it to launch. There is something wrong with the permissions. If you right click on the blank background once the container is running you can bring up xterm. Then `sudo su` and run the fmd.exe that way. 

it's not great to run it as root, but I'm not exposing it to the web so it's not that big of a deal. That at least gets it working.

**Comment by abwezi** [comment]
> > @DieselTech Did you resolve this? I am trying other alternatives ATM because I am also affected by this problem, but I am not liking them as much. There seems to be nothing else to easily automate only downloading the newest chapters of a manga from instead of the entire thing.
> 
> Yeah I was able to get it to launch. There is something wrong with the permissions. If you right click on the blank background once the container is running you can bring up xterm. Then `sudo su` and run the fmd.exe that way.
> 
> it's not great to run it as root, but I'm not exposing it to the web so it's not that big of a deal. That at least gets it working.

That would need done every time the container restarts won't it?

**Comment by abwezi** [comment]
> > That would need done every time the container restarts won't it?
> 
> Yeah, it's just a work around currently. Usually my containers stay running for weeks on end without having to reboot so I don't mind the workaround right now until something more permanent comes along.

Okay thank you @DieselTech for pointing me in the right direction, so what I did instead, that seems to be working automatically, is this

Installed the latest from the docker compose. I added a line to mount my existing media folder on my host drive.

After it installed and ran the container I went into docker terminal and ran `chmod ugo+rwx /app/FMD2/fmd.exe`

restarted container and it comes right up. Now I'm going to disable update nags so that I'm never again tempted to fix something that is not broken lol. Thank you again

**Comment by DieselTech** [comment]
> Now I'm going to disable update nags so that I'm never again tempted to fix something that is not broken lol. Thank you again

To be fair the update to FMD2 was valid. Deleting the previous docker image when a new version comes out is the real problem here. That's kind of against the spirit of docker. It prevents us from rolling back when there is a problem with updates (like this)
